---

- name: Enable repository
  hosts: all
  become: yes
  tasks:

    - name: Enable repository in redhat.repo
     
      lineinfile:
        
        path: /etc/yum.repos.d/redhat.repo
        regexp: '^(enabled\s*=\s*)0$'
        line: '\11'
      notify: Update package cache


    - name: Updaye package cache
      command: yum makecache
      ignore_errors: true
     
