---
- name: Configure static IP address for all hosts
  hosts: all
  become: yes
  tasks:
    - name: Set network configuration
      template:
        src: templates/network-config.j2
        dest: "/etc/sysconfig/network-scripts/ifcfg-eth0"
      vars:
        ip_address: "{{ ip_address }}"
        netmask: "255.255.240.0"
        gateway: "192.168.176.1"
