---
- hosts: all
  become: true
  tasks:
    - name: install python3
      yum:
        name: python3

    - name: install apache2 package
      yum:
        name: httpd
        state: absent

    - name: install PHP support for Apache
      yum:
        name:
        state: absent
          -  php
          -  php-mysqlnd # Add any other PHP modules you need

    - name: restart Apache
      service:
        name: httpd
        state: restarted

